name: API E2E RestAssured Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      backend:
        image: node:20
        ports:
          - 4000:4000
        options: >-
          --health-cmd="curl http://localhost:4000/api/health || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        env:
          PORT: 4000
        # You must provide a Dockerfile or a ready image for your backend, or replace this with your deployment solution.

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Run API E2E tests
        run: mvn test